sudo: false
language: rust
matrix:
  allow_failures:
#    - rust: nightly
  fast_finish: true
  include:
#    - rust: stable
#    - rust: beta
    - rust: nightly

before_script:
  - export PGPASSWORD="postgres"
  - psql -c "DROP DATABASE IF EXISTS rustyblog;" -U postgres
  - diesel setup

script:
  - cargo test --no-run

cache: cargo

addons:
  postgresql: "9.4"