sudo: false
language: rust
matrix:
  fast_finish: true
  include:
    - rust: nightly
#    - rust: beta
#    - rust: stable

before_script:
  - export PGPASSWORD="postgres"
  - cargo install diesel_cli
  - diesel setup --database-url='postgres://postgres:postgres@localhost/rustyblog'

script:
- cargo test --no-run

cache:
  apt: true
  directories:
  - ~/.cargo/registry
  - target/debug/deps
  - target/debug/build

addons:
  postgresql: "9.4"