sudo: false
language: rust
matrix:
  fast_finish: true
  include:
    - rust: nightly
#    - rust: beta
#    - rust: stable

before_script:
  - psql -c "DROP DATABASE IF EXISTS rustyblog_test;" -U postgres
  - psql -c "create database rustyblog_test;" -U postgres

script:
- cargo test --no-run

cache:
  apt: true
  directories:
  - target/debug/deps
  - target/debug/build

addons:
  postgresql: "9.4"
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev