sudo: false
language: rust
cache: cargo
matrix:
  fast_finish: true
  include:
    - rust: nightly
#    - rust: beta
#    - rust: stable

before_script:
  - export PGPASSWORD="postgres"
  - psql -c "DROP DATABASE IF EXISTS rustyblog;" -U postgres
  - diesel setup

script:
  - cargo test --no-run

addons:
  postgresql: "9.4"